#  ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

name: $(Year:yy).$(Month).$(DayOfMonth).$(BuildID)-$(SourceBranchName)

variables:
  buildConfiguration: 'Release'
  agentImage: "windows-latest"
  buildPlatform: 'Any CPU'

jobs:
- job: 'PublishEFCore'
  pool:
    vmImage: $(AgentImage)
  steps:
  - task: CmdLine@2
    displayName: 'Publish EF Core migration scripts'
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/Pcb.Database
      script:
        dotnet ef --version &&
        dotnet ef migrations script –s $(Build.SourcesDirectory)/Pcb.Database -o $(build.artifactstagingdirectory)/migrations/scripts.sql -i
  - task: PublishBuildArtifacts@1
    displayName: 'Publish EFCore Migrations'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)/migrations'
      artifactName: 'Migrations'
