/**
 * @notes
 * This spec file has been generated by oughtaTest
 * Based heavily upon the scuri work of Georgi Parlakov - https://github.com/gparlakov/scuri
 * Assuming that the app contains autoSpy and correct path declaration in tsconfig e.g. "autospy": ["src/app/tests/auto-spy"]
 * Also assuming package contains angularMaterial>8 and ng-mocks as a devDependencies - https://github.com/ike18t/ng-mocks#readme
 */
import { waitForAsync, ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';


import { MatButtonModule } from '@angular/material/button';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { RouterTestingModule } from '@angular/router/testing';

import { autoSpy } from 'autospy';
import { MockComponent } from 'ng-mocks';
import { of, Subject } from 'rxjs';
import { AuthenticationService } from '@services/authentication.service';
import { UserProfileService } from '@services/user-profile.service';
import { WelcomeComponent } from './welcome.component';
import { HttpClientModule } from '@angular/common/http';

type Spy<T> = T & jasmine.SpyObj<T>;

describe('WelcomeComponent', () => {
	let component: WelcomeComponent;
	let fixture: ComponentFixture<WelcomeComponent>;


	const authenticationServiceSpy: Spy<AuthenticationService> = autoSpy(AuthenticationService);
	const userProfileServiceSpy: Spy<UserProfileService> = autoSpy(UserProfileService);
	// exampleServiceSpy.exampleMethod.and.returnValue(of(fakeItem)) - for all items that are called in ngOnInit

	beforeEach(waitForAsync(() => {
		TestBed.configureTestingModule({
			imports: [
				MatButtonModule,
				NoopAnimationsModule,
				RouterTestingModule,
				HttpClientModule
			],
			declarations: [
				WelcomeComponent,
				// MockComponent(ComponentsUsedInTheHTML)
			],
			providers: [
				{ provide: AuthenticationService, userValue: authenticationServiceSpy },
				{ provide: UserProfileService, userValue: userProfileServiceSpy },
			]
		}).compileComponents();
	}));

	beforeEach(() => {

		fixture = TestBed.createComponent(WelcomeComponent);
		component = fixture.componentInstance;
		fixture.detectChanges();
	});

	it('should create', () => {
		expect(component).toBeTruthy();
	});

	describe('when ngOnInit is called it should', () => {
		// remove what is not required
		beforeEach(() => {

		});

		it('should ...', () => {
			// arrange
			// act
			// component.ngOnInit();
			// assert
			// expect(c).toEqual
		});
	});


});
