/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MeasurementModel } from './ingredient-model';
import { ReferenceItemFull } from './reference.model';

export interface Conversion {
	id?: number;
	ingredientId?: number;
	baseState?: ReferenceItemFull;
	baseMeasurementUnit: MeasurementModel;
	baseQuantity: number;

	convertToState?: ReferenceItemFull;
	convertToMeasurementUnit: MeasurementModel;
	convertToQuantity: number;
	answer: string;
	/**
	 * eg flour is usually purchased in kg and used in cups (volume)
	 */
	preference?: number;
}
