/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StepByStepInstructions {
	_id?: string;
	/**
	 * Which step number
	 */
	number: number;
	/**
	 * Step instructions
	 */
	step: string;
	/**
	 * Array of ingredient IDs used in this step
	 */
	ingredients?: Array<string>;
	/**
	 * Array of ingredient names (just strings) used in this step
	 */
	equipment?: Array<string>;
}
